### ISSUE TITLE
cant withdraw collateral, Fail with error 'Insufficient Collateral Balance to withdraw.'

### ISSUE THREAD

**Issue by akbarwijayaa** [KonScanner/synthr-farming#4]
can u help me to solve this ser?, code say success, but when im check on the explorer it say, Fail with error 'Insufficient Collateral Balance to withdraw.'

**Comment by akbarwijayaa** [comment]
![Screenshot 2024-05-27 125033](https://github.com/KonScanner/synthr-farming/assets/92082017/1e865098-090a-488e-ba25-43cd82d7a81a)
im reducing amount to withdraw but nothing happen

**Comment by KonScanner** [comment]
Add some collateral manually before running the script @akbarwijayaa, through the UI.
