### ISSUE TITLE
execution reverted: Insufficient Collateral Balance to withdraw.

### ISSUE THREAD

**Issue by luqmanfajar** [KonScanner/synthr-farming#6]
i've add manually collatteral from ui, but still getting this error

**Comment by KonScanner** [comment]
It is working fine if you add enough tokens as collateral via UI before starting it off.

I am not planning to keep supporting this weekend project, sorry.

Follow instructions and modify the code (if you need to), and it should work:
![image](https://github.com/user-attachments/assets/98b36233-6c4f-494d-a0db-e1efd84bdb1f)
